export default {
    // 图标
    IC_ADD			: 'assets://res/icon/ic_add.png',
    IC_ADMIN			: 'assets://res/icon/ic_admin.png',
    IC_ALARM			: 'assets://res/icon/ic_alarm.png',
    IC_CLOCK			: 'assets://res/icon/ic_clock.png',
    IC_CLOSE			: 'assets://res/icon/ic_close.png',
    IC_DASHBOARD			: 'assets://res/icon/ic_dashboard.png',
    IC_DELETE			: 'assets://res/icon/ic_delete.png',
    IC_DEVICE			: 'assets://res/icon/ic_device.png',
    IC_DIRT_HUMIDITY			: 'assets://res/icon/ic_dirt_humidity.png',
    IC_DIRT_TEMPERATURE			: 'assets://res/icon/ic_dirt_temperature.png',
    IC_EDIT			: 'assets://res/icon/ic_edit.png',
    IC_FERTILIZATION			: 'assets://res/icon/ic_fertilization.png',
    IC_FORBIDDEN			: 'assets://res/icon/ic_forbidden.png',
    IC_GUEST			: 'assets://res/icon/ic_guest.png',
    IC_HISTORY			: 'assets://res/icon/ic_history.png',
    IC_HUMIDITY			: 'assets://res/icon/ic_humidity.png',
    IC_INFO			: 'assets://res/icon/ic_info.png',
    IC_LOCK			: 'assets://res/icon/ic_lock.png',
    IC_MORE			: 'assets://res/icon/ic_more.png',
    IC_OPERATION			: 'assets://res/icon/ic_operation.png',
    IC_PEOPLE			: 'assets://res/icon/ic_people.png',
    IC_PICK_BLUE			: 'assets://res/icon/ic_picked_blue.png',
    IC_STAFF			: 'assets://res/icon/ic_staff.png',
    IC_SUN			: 'assets://res/icon/ic_sun.png',
    IC_TABLE			: 'assets://res/icon/ic_table.png',
    IC_TEMPERATURE			: 'assets://res/icon/ic_temperature.png',
    IC_USER_LIST			: 'assets://res/icon/ic_user_list.png',
    IC_WATERING			: 'assets://res/icon/ic_watering.png',
    IC_KEY			: 'assets://res/icon/ic_key.png',
    IC_CONTROL			: 'assets://res/icon/ic_control.png',
    IC_CONTROL_ACTIVE			: 'assets://res/icon/ic_control_active.png',
    IC_HOME			: 'assets://res/icon/ic_home.png',
    IC_HOME_ACTIVE			: 'assets://res/icon/ic_home_active.png',
    IC_ME			: 'assets://res/icon/ic_me.png',
    IC_ME_ACTIVE			: 'assets://res/icon/ic_me_active.png',
    IC_SCHEDULE			: 'assets://res/icon/ic_schedule.png',
    IC_SCHEDULE_ACTIVE			: 'assets://res/icon/ic_schedule_active.png',
    //　图片
    IMG_BACKGROUND			: 'assets://res/img/background.png',
    IMG_DIVER			: 'assets://res/img/diver_gray.png',
    IMG_LOGO			: 'assets://res/img/logo.png',
    IMG_LOGO_DESCRIPTION			: 'assets://res/img/logo_description.png',
    IMG_LOGO_BLACK			: 'assets://res/img/logo_nav.png',

}