# Generated by Django 2.0 on 2017-12-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isOn', models.IntegerField(default=0)),
                ('repeatType', models.IntegerField(default=0)),
                ('repeatCircle', models.CharField(default='0', max_length=7)),
                ('hour', models.IntegerField(default='0')),
                ('minute', models.IntegerField(default='0')),
                ('actions', models.CharField(max_length=1024)),
            ],
        ),
    ]
