# Generated by Django 2.0 on 2018-03-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2017)),
                ('month', models.IntegerField(default=1)),
                ('day', models.IntegerField(default=1)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2017)),
                ('month', models.IntegerField(default=1)),
                ('day', models.IntegerField(default=1)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2017)),
                ('month', models.IntegerField(default=1)),
                ('day', models.IntegerField(default=1)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isOn', models.IntegerField(default=0)),
                ('repeatType', models.IntegerField(default=0)),
                ('repeatCircle', models.CharField(default='0', max_length=7)),
                ('hour', models.IntegerField(default='0')),
                ('minute', models.IntegerField(default='0')),
                ('actions', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2017)),
                ('month', models.IntegerField(default=1)),
                ('day', models.IntegerField(default=1)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('light', models.FloatField(default=-100)),
                ('air_temperature', models.FloatField(default=-100)),
                ('dirt_temperature', models.FloatField(default=-100)),
                ('air_humidity', models.FloatField(default=-100)),
                ('dirt_humidity', models.FloatField(default=-100)),
                ('device_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2017)),
                ('month', models.IntegerField(default=1)),
                ('day', models.IntegerField(default=1)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
    ]
