# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isCanModify',
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.CharField(blank=True, max_length=200, verbose_name='签名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='昵称'),
        ),
    ]
